"""create cartid column in order table

Revision ID: e58d7d10ec03
Revises: b4cc08d3af66
Create Date: 2025-10-13 19:17:27.165996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58d7d10ec03'
down_revision: Union[str, Sequence[str], None] = 'b4cc08d3af66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_id_key'), 'cart', type_='unique')
    op.add_column('orders', sa.Column('cart_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'cart', ['cart_id'], ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'cart_id')
    op.create_unique_constraint(op.f('cart_id_key'), 'cart', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
